###

POST http://localhost:3001/api/notes HTTP/1.1
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MWY1ZDM4NDgxMzBlYTc2NmQ2NmU3ZiIsInVzZXJuYW1lIjoiZmVyIiwiaWF0IjoxNjgwNjUwMjY2fQ.0UheAwJbL-J077d-zYLT2hDldSVZN2_l1tmhmD0K5kE

{
  "title":"www"
  
}

###
GET http://localhost:3001/api/notes/ HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MWY1ZDM4NDgxMzBlYTc2NmQ2NmU3ZiIsInVzZXJuYW1lIjoiZmVyIiwiaWF0IjoxNjgwNjUwMjY2fQ.0UheAwJbL-J077d-zYLT2hDldSVZN2_l1tmhmD0K5kE

###
GET http://localhost:3001/api/notes/640fc6965768b012773eb664 HTTP/1.1

###

DELETE http://localhost:3001/api/notes/6422450a33b2e12e4b3b0319 HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MWY1ZDM4NDgxMzBlYTc2NmQ2NmU3ZiIsInVzZXJuYW1lIjoiZmVyIiwiaWF0IjoxNjc5NzkwODEyfQ.D7Pryd61gG_-E83U7sYTBIVdnslNg8Lv_4mkwOtaMv4

###
PUT http://localhost:3001/api/notes/642cc9caab26d8ffb716874c HTTP/1.1
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MWY1ZDM4NDgxMzBlYTc2NmQ2NmU3ZiIsInVzZXJuYW1lIjoiZmVyIiwiaWF0IjoxNjgwNjUwMjY2fQ.0UheAwJbL-J077d-zYLT2hDldSVZN2_l1tmhmD0K5kE

{
  "title":"hola",
  "status":false
}